In [1]:
import tensorflow as tf

In [2]:
tf.InteractiveSession()

 tf.zeros() takes a tensor shape (represented as a
Python tuple) and returns a tensor of that shape filled with zeros.

In [3]:
tf.zeros(2)

<tf.Tensor 'zeros:0' shape=(2,) dtype=float32>

 Evaluate the value of a tensor

In [4]:
a=tf.zeros(2)
a.eval()

array([0., 0.], dtype=float32)

We can call tf.zeros() and tf.ones() to create and display tensors of various sizes


In [5]:
b=tf.zeros((2,3))
b.eval()

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [6]:
c=tf.ones((2,2,2))
c.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

What if we’d like a tensor filled with some quantity besides 0/1? The tf.fill()
method provides a nice shortcut for doing so 

In [7]:
b=tf.fill((2,2),value=5.)
b.eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

tf.constant is another function, similar to tf.fill, which allows for construction
of tensors that shouldn’t change during the program execution

In [8]:
a=tf.constant(3)
a.eval()

3

## Sampling random tensors

sample each entry in the tensor from a random distribution. 
tf.random_normal allows for each entry in a tensor of specified shape to be sampled from a Normal
distribution of specified mean and standard deviation

In [9]:
a = tf.random_normal((2, 2), mean=0, stddev=1)
a.eval()

array([[-1.1531013 ,  0.97032565],
       [ 1.3084397 ,  0.69101864]], dtype=float32)

One thing to note is that machine learning systems often make use of very large ten‐
sors that often have tens of millions of parameters. When we sample tens of millions
of random values from the Normal distribution, it becomes almost certain that some
sampled values will be far from the mean. Such large samples can lead to numerical
instability, so it’s common to sample using tf.truncated_normal() instead of tf.ran
dom_normal(). This function behaves the same as tf.random_normal() in terms of
API, but drops and resamples all values more than two standard deviations from the
mean.

tf.random_uniform() behaves like tf.random_normal() except for the fact that ran‐
dom values are sampled from the Uniform distribution over a specified range


In [10]:
a = tf.random_uniform((2, 2), minval=-2, maxval=2)


In [11]:
a.eval()

array([[ 1.0833039 , -1.594109  ],
       [-0.14467382, -1.160255  ]], dtype=float32)

## Tensor Addition and Scaling

In [12]:
c = tf.ones((2, 2))
d = tf.ones((2, 2))
e = c + d
e.eval()

array([[2., 2.],
       [2., 2.]], dtype=float32)

In [13]:
f=2*e
f.eval()

array([[4., 4.],
       [4., 4.]], dtype=float32)

Tensors can also be multiplied this way. Note, however, when multiplying two tensors
we get elementwise multiplication and not matrix multiplication.

In [15]:
c = tf.fill((2,2), 2.)
d=tf.fill((2,2),7.)
e=c*d
e.eval()

array([[14., 14.],
       [14., 14.]], dtype=float32)

## Matrix Operations

tf.eye() allows for
fast construction of identity matrices of desired size 

In [16]:
a = tf.eye(4)
a.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

Let’s construct a diagonal matrix with
ascending values along the diagonal. First construct a vector of ascending values by using tf.range(start, limit, delta). Limit is excluded from the range and delta is the step size. The resulting vector can then be input into tf.diag(diagonal), which will construct the matrix with the specified diagonal. 

In [17]:
r = tf.range(1, 5, 1)
r.eval()

array([1, 2, 3, 4])

In [18]:
d = tf.diag(r)
d.eval()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

To compute the transpose, use:  tf.matrix_transpose().

In [19]:
a = tf.ones((2, 3))
a.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
at = tf.matrix_transpose(a)
at.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

To perform matrix multiplication, use tf.mamul(). 

In [21]:
a = tf.ones((2, 3))
a.eval()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [22]:
b = tf.ones((3, 4))
b.eval()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [23]:
c = tf.matmul(a, b)
c.eval()

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

## Tensor Types

It’s possible to to create tensors of specified types by setting dtype in tensor
construction functions. Furthermore, given a tensor, it’s possible to change its type
using casting functions such as tf.to_double(), tf.to_float(), tf.to_int32(),
tf.to_int64(), and others

In [24]:
a=tf.ones((2,2),dtype=tf.int32)

In [25]:
a.eval()

array([[1, 1],
       [1, 1]])

In [26]:
b = tf.to_float(a)
b.eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

## Tensor Shape Manipulations 

 At different times, it can be useful to view
the same set of numbers as forming tensors with different shapes. tf.reshape()
allows tensors to be converted into tensors with different shapes 

In [27]:
a = tf.ones(8)
a.eval()

array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [28]:
 b = tf.reshape(a, (4, 2))
b.eval()

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [29]:
 c = tf.reshape(a, (2, 2, 2))
 c.eval()

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

While all necessary shape manipulations can be
performed with tf.reshape(), sometimes it can be convenient to perform simpler
shape manipulations using functions such as tf.expand_dims or tf.squeeze.
tf.expand_dims adds an extra dimension to a tensor of size 1. It’s useful for increas‐
ing the rank of a tensor by one (for example, when converting a rank-1 vector into a
rank-2 row vector or column vector). tf.squeeze, on the other hand, removes all
dimensions of size 1 from a tensor. It’s a useful way to convert a row or column vector
into a flat vector.


 tf.Tensor.get_shape() allows users query the shape of a tensor. 

In [30]:
a = tf.ones(2)
a.get_shape()

TensorShape([Dimension(2)])

In [31]:
a.eval()

array([1., 1.], dtype=float32)

In [32]:
b = tf.expand_dims(a, 0)
b.get_shape()

TensorShape([Dimension(1), Dimension(2)])

In [33]:
b.eval()

array([[1., 1.]], dtype=float32)

In [34]:
c = tf.expand_dims(a, 1)
c.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [35]:
c.eval()

array([[1.],
       [1.]], dtype=float32)

In [36]:
d = tf.squeeze(b)
d.get_shape()

TensorShape([Dimension(2)])

In [37]:
d.eval()

array([1., 1.], dtype=float32)